import _ from 'lodash'
import VueQuery from 'vuequery'

// Returns true if the component's parent tree contains <Nuxt>
// (meaning it's part of the page, and not a global component)
export function isPageChild(vm) {
  try {
    return VueQuery(vm).parents('Nuxt').length || false
  } catch {
    return false
  }
}

// Returns true if component has a fetch method defined on it
export function hasFetch(vm) {
  return vm.$options && typeof vm.$options.fetch === 'function' && !vm.$options.fetch.length
}

// Scroll to a section/element on the page
export function selectContent(path) {
  const elements = Array.from(document.querySelectorAll('[data-sw-path]'))
  const element = elements.find(el => el.dataset.swPath === path)

  if (!element) return

  element.scrollIntoView({
    behavior: 'smooth',
    block: 'center'
  })
}

// Override a root CSS variable on the document object
export function setCssVariable(path, value) {
  if (!isCssVariableGroup(path)) return

  // Set variable on document root
  const variableName = `--${path.replace(/\./g, '-')}`
  document.documentElement.style.setProperty(variableName, value)
}

// Returns string of CSS variables to inject as a stylesheet
// TODO split into two functions
export function generateCssVariables(storeSettings) {
  const keyNames = getVariableGroups()
  const variables = generateVariableList(storeSettings, keyNames)

  if (process.browser) {
    // Set variables on document root
    variables.map(cssVar => {
      let [variableName, value] = cssVar.split(':')
      value = value.slice(0, -1) // Remove the semicolon otherwise the value gets ignored
      document.documentElement.style.setProperty(variableName, value)
    })
  } else {
    // Return variables as CSS stylesheet string
    return (
      '/*\n' +
      '!!! AUTOGENERATED FILE !!!\n' +
      `These variables were set by the swell-editor module during server build.\n` +
      '*/\n' +
      `:root {\n${variables.join('\n')}\n}`
    )
  }
}

// Returns true if settings group key from the provided path
// is configured used for CSS variable generation
export function isCssVariableGroup(path) {
  const groupKey = path.split('.')[0]
  const variableGroups = getVariableGroups()
  return variableGroups.includes(groupKey)
}

// Returns array of settings object keys configured for CSS variable generation
function getVariableGroups() {
  const defaultGroups = ['colors', 'typography']
  const optionsGroups = '<%= options.cssVariableGroups %>'
  const customGroups = optionsGroups ? optionsGroups.split(',') : []
  const mergedGroups = new Set([...defaultGroups, ...customGroups])

  return Array.from(mergedGroups)
}

// Generate array of CSS variables with values
function generateVariableList(settings, keyNames) {
  const typeScale = {
    ratioVarName: '--' + _.kebabCase('typography.scale_ratio'),
    baseSizeVarName: '--' + _.kebabCase('typography.scale_base_size'), // TODO implement base factor
    steps: _.range(-6, 17),
    getStepValue: (step, ratio) => _.round(ratio ** step, 3) + 'rem'
  }
  const variables = []

  keyNames.map((group, index) => {
    // Convert nested properties into flattened kebab case object
    const palette = flattenColorPalette(settings[group])

    // Turn each property into a CSS variable name with value
    for (const [key, value] of Object.entries(palette)) {
      const varName = `--${group}-${_.kebabCase(key)}`

      // Add variable to list
      variables.push(`${varName}: ${value};`)

      // Generate modular type scale
      if (varName === typeScale.ratioVarName) {
        const ratio = parseFloat(value) || 1.125
        typeScale.steps.map(step =>
          variables.push(`--type-scale-${step}: ${typeScale.getStepValue(step, ratio)};`)
        )
      }
    }
  })

  return variables
}

// Tailwind utility for transforming object into kebab-case string
// https://github.com/tailwindcss/tailwindcss/blob/master/src/util/flattenColorPalette.js
function flattenColorPalette(colors) {
  const result = _(colors)
    .flatMap((color, name) => {
      if (!_.isObject(color)) {
        return [[name, color]]
      }

      return _.map(color, (value, key) => {
        const suffix = key === 'default' ? '' : `-${key}`
        return [`${name}${suffix}`, value]
      })
    })
    .fromPairs()
    .value()

  return result
}
