import { getCssVariables } from '../utils';

// Returns string of CSS variables to inject as a stylesheet
export function generateCssVariables(settings) {
  const variables = getCssVariables(settings);

  // Return variables as CSS stylesheet string
  return [
    '/*',
    '',
    '!!! AUTOGENERATED FILE !!!',
    'These variables were generated by the swell-editor module during build.',
    '',
    `- Timestamp: ${new Date()}`,
    `- Node env: ${process.env.NODE_ENV}`,
    `- Using API settings: ${process.env.SWELL_EDITOR || false}`,
    '',
    '*/',
    `:root {\n${variables.join('\n')}\n}`,
  ].join('\n');
}
